os:
  - linux

language: go

go:
  - 1.13.x

env:
  global:
    - PIONS_LOG_WARN=all
    - PIONS_LOG_ERROR=all
  matrix:
    - BUILD_DEPTYPE=gomod

# disable travis install
install:
  - true

# run tests with and without race detection
script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)
  - GOTFLAGS="-race" bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
  directories:
    - $GOPATH/src/gx
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
